import{a as w,S,i as u}from"./assets/vendor-5YrzWRhu.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function r(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(t){if(t.ep)return;t.ep=!0;const n=r(t);fetch(t.href,n)}})();const b="51737021-87f818cc1ae3d02e4bfd7c05a",v="https://pixabay.com/api/",q=15;async function E(o,e=1){const r={key:b,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:q},{data:i}=await w.get(v,{params:r});return i}const h=document.querySelector(".gallery"),y=document.querySelector("#load-more"),m=document.querySelector(".loader"),R=new S(".gallery a",{captionsData:"alt",captionDelay:250});function M(o){const e=o.map(r=>`
      <li class="card">
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy"/>
        </a>
        <ul class="meta">
          <li>❤ ${r.likes}</li>
          <li>👁 ${r.views}</li>
          <li>💬 ${r.comments}</li>
          <li>⬇ ${r.downloads}</li>
        </ul>
      </li>`).join("");h.insertAdjacentHTML("beforeend",e),R.refresh()}function A(){h.innerHTML=""}function B(){m.classList.remove("is-hidden")}function P(){m.classList.add("is-hidden")}function $(){y.classList.remove("is-hidden")}function s(){y.classList.add("is-hidden")}function N(){const o=document.querySelector(".gallery .card");if(!o)return;const{height:e}=o.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function O(){u.error({position:"topRight",title:"No results",message:"Sorry, no images found. Try another query!"})}function x(){u.info({position:"topRight",title:"Info",message:"We're sorry, but you've reached the end of search results."})}function I(o="Something went wrong. Please try again."){u.error({position:"topRight",title:"Error",message:o})}const p=document.querySelector(".form"),_=p.querySelector('input[name="search-text"]'),H=document.querySelector("#load-more");let g="",d=1,f=0,a=0,c=!1;s();p.addEventListener("submit",async o=>{o.preventDefault();const e=_.value.trim();e&&(g=e,d=1,a=0,A(),s(),await L())});H.addEventListener("click",async()=>{d+=1,await L(!0)});async function L(o=!1){if(!c)try{c=!0,B();const{hits:e=[],totalHits:r=0}=await E(g,d);if(f=r,!o&&e.length===0){s(),O();return}M(e),a+=e.length,a<f?$():(s(),a>0&&x()),o&&N()}catch(e){s(),I((e==null?void 0:e.message)||"Network error")}finally{P(),c=!1}}
//# sourceMappingURL=index.js.map
