import{a as w,S,i as f}from"./assets/vendor-5YrzWRhu.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();const b="51737021-87f818cc1ae3d02e4bfd7c05a",v="https://pixabay.com/api/",q=15;async function R(r,e=1){const o={key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:q},{data:i}=await w.get(v,{params:o});return i}const y=document.querySelector(".gallery"),h=document.querySelector("#load-more"),m=document.querySelector(".loader"),A=new S(".gallery a",{captionsData:"alt",captionDelay:250});function B(r){const e=r.map(o=>`
      <li class="card">
        <a href="${o.largeImageURL}">
          <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy"/>
        </a>
        <ul class="meta">
          <li>❤ ${o.likes}</li>
          <li>👁 ${o.views}</li>
          <li>💬 ${o.comments}</li>
          <li>⬇ ${o.downloads}</li>
        </ul>
      </li>`).join("");y.insertAdjacentHTML("beforeend",e),A.refresh()}function E(){y.innerHTML=""}function M(){m.classList.remove("is-hidden")}function $(){m.classList.add("is-hidden")}function P(){h.classList.remove("is-hidden")}function s(){h.classList.add("is-hidden")}function O(){const r=document.querySelector(".gallery .card");if(!r)return;const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function x(){f.error({position:"topRight",title:"No results",message:"Sorry, no images found. Try another query!"})}function I(){f.info({position:"topRight",title:"Info",message:"We're sorry, but you've reached the end of search results."})}const p=document.querySelector(".form"),N=p.querySelector('input[name="search-text"]'),_=document.querySelector("#load-more");let g="",u=1,d=0,a=0,c=!1;s();p.addEventListener("submit",async r=>{r.preventDefault();const e=N.value.trim();e&&(g=e,u=1,a=0,E(),s(),await L())});_.addEventListener("click",async()=>{u+=1,await L(!0)});async function L(r=!1){if(!c)try{c=!0,M();const{hits:e=[],totalHits:o=0}=await R(g,u);if(d=o,!r&&e.length===0){s(),x();return}B(e),a+=e.length,a<d?P():(s(),a>0&&I()),r&&O()}catch{s()}finally{$(),c=!1}}
//# sourceMappingURL=index.js.map
